# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96bc4dbd1a1af0fda399289a6506304bedb844847f6dfe2ef02d392fad4abdf3d661230e8c0678d90bd6647cda051841951897db827f2680c22342f1ae34ad5d

test:
  secret_key_base: 50f31a56b1f0549d7424de8f30fc3e48b719015c47ea28ee81acee44fd368a6c0af8f95810beac3d06149373ff057a9b3cb5b3ef86d3f94080cae55751265e72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
